#+begin_src emacs-lisp
  ;;; -*- lexical-binding: t; -*-
#+end_src
* Startup
** Startup Profiling
   
Profile how long it takes for Emacs to startup
   
#+begin_src emacs-lisp
  (add-hook 'emacs-startup-hook
            (lambda ()
              (message "Emacs ready in %s with %d garbage collections."
                       (format "%.2f seconds"
                               (float-time
                                (time-subtract after-init-time before-init-time)))
                       gcs-done)))
#+end_src

** Startup Screen

Start Emacs with an empty Org-mode buffer in the home directory.
   
#+begin_src emacs-lisp
  (use-package emacs
    :init
    (setq inhibit-startup-screen t
          initial-scratch-message nil
          initial-major-mode 'org-mode
          default-directory "~/"))
#+end_src

** Mitsuharu Yamamoto Emacs Configuration

Since this emacs configuration is targetted at Mitsuharu Yamamoto’s Emacs build for macOS, we have to switch what each modifier key does back to the default.
   
#+begin_src emacs-lisp
  (use-package emacs
    :init
    (setq mac-option-modifier        'meta
          mac-right-option-modifier  'meta
          mac-command-modifier       'super
          mac-right-command-modifier 'super))
#+end_src
   
* User Interface

#+begin_src emacs-lisp
  (use-package emacs
    :diminish (visual-line-mode)
    :init
    (menu-bar-mode -1)
    (tool-bar-mode -1)
    (scroll-bar-mode -1)
    (blink-cursor-mode -1)
    (global-visual-line-mode)
    (column-number-mode 1)
    (global-display-line-numbers-mode 1)
    (fringe-mode 5))
#+end_src

** Fonts

#+begin_src emacs-lisp
  (set-frame-font "Inconsolata for Powerline 20" nil t)
#+end_src

*** All The Icons

#+begin_src emacs-lisp
  (use-package all-the-icons)
#+end_src

** Theme

#+begin_src emacs-lisp
  (add-to-list 'custom-theme-load-path "~/.emacs.d/themes")

  (use-package kaolin-themes
    :config
    (load-theme 'kaolin-breeze t))
#+end_src

** Visual Bell

Instead of playing an annoying sound when an error occurs, breifly invert the colors of the modeline.

#+begin_src emacs-lisp
  (defun meet/visual-bell-modeline-flash ()
    (let ((frame (selected-frame)))
      (run-with-timer
       0.1 nil
       #'(lambda (frame)
           (let ((inhibit-quit)
                 (inhibit-redisplay t))
             (invert-face 'mode-line frame)
             (invert-face 'mode-line-inactive frame)))
       frame)
      (let ((inhibit-quit)
            (inhibit-redisplay t))
        (invert-face 'mode-line frame)
        (invert-face 'mode-line-inactive frame))))

  (setq ring-bell-function 'meet/visual-bell-modeline-flash)
#+end_src
   
** HL Line

HL-Line mode is a minor mode that highlights the current line.

#+begin_src emacs-lisp
  (use-package hl-line
    :diminish
    :hook (after-init . global-hl-line-mode))
#+end_src

** Rainbow Mode

Rainbow mode is a minor-mode which highlights text representing color codes by settings the background color of the text accordingly. This works with ~rgb()~ and hexadecimal codes.

#+begin_src emacs-lisp
  (use-package rainbow-mode
    :diminish
    :hook (after-init . rainbow-mode))
#+end_src

** Rainbow Delimiters

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :diminish
    :hook ((org-mode prog-mode-hook) . rainbow-delimiters-mode))
#+end_src

* Evil
** Evil Mode

#+begin_src emacs-lisp
  (use-package evil
    :diminish
    :bind
    (:map evil-motion-state-map
          ("j" . 'evil-next-visual-line)
          ("k" . 'evil-previous-visual-line))
    ("s-w" . 'kill-this-buffer)
    (:map evil-visual-state-map
          ("j" . 'evil-next-visual-line)
          ("k" . 'evil-previous-visual-line))
    :init
    (setq evil-want-integration t
          evil-want-keybinding nil)
    (evil-mode))
#+end_src

** Evil Leader

#+begin_src emacs-lisp
  (use-package evil-leader
    :init
    :after (evil)
    :diminish
    :init
    (global-evil-leader-mode)
    :config
    (evil-leader/set-leader "<SPC>")
    (evil-leader/set-key
      "<SPC>" 'delete-other-windows
      "w" 'kill-this-buffer
      "k" 'kill-buffer))
#+end_src

** Evil Org

#+begin_src emacs-lisp
  (use-package evil-org
    :after (org evil)
    :diminish
    :hook (org-mode . evil-org-mode))
#+end_src

** Evil Surround

This minor-mode emulates surround.vim in Evil mode.

#+begin_src emacs-lisp
  (use-package evil-surround
    :after (evil)
    :diminish
    :init
    (global-evil-surround-mode 1))
#+end_src

** Evil Goggles

This minor mode displays a visual hint when editing with Evil mode.

#+begin_src emacs-lisp
  (use-package evil-goggles
    :after (evil)
    :diminish
    :config
    (evil-goggles-use-diff-faces)
    :init
    (evil-goggles-mode))
#+end_src

** Evil Commentary

This is a minor-mode that makes it easier to comment out lines of code.

|---------+----------------------+---------------------------------------------------|
| Keybind | Command              | Description                                       |
|---------+----------------------+---------------------------------------------------|
| =gc=      | evil-commentary      | Comments out the target of a motion.              |
| =gy=      | evil-commentary-yank | Comments out the target of a motion and yanks it. |
| =Super+/= | evil-commentary-line | Comments out the current line.                    |
|---------+----------------------+---------------------------------------------------|

#+begin_src emacs-lisp
  (use-package evil-commentary
    :after (evil)
    :diminish
    :init
    (evil-commentary-mode))
#+end_src

** Evil Collection

#+begin_src emacs-lisp
  (use-package evil-collection
    :init
    (evil-collection-init))
#+end_src

** Evil TeX

This minor-mode is a Evil toolbox for LaTeX editing.

Text Object Table

|-----+--------------+
| Key | Abbreviation |
|-----+--------------+
| =c=   | command      |
| =e=   | environment  |
| =m=   | math         |
| =M=   | display math |
| =d=   | delimiters   |
| =S=   | sections     |
| =^=   | superscript  |
| =_=   | subscript    |
| =T=   | table cell   |
|-----+--------------+

Environment Table

|-----+-------------|
| Key | Environment |
|-----+-------------|
| ~e~   | equation    |
| ~E~   | equation*   |
| ~f~   | figure      |
| ~i~   | itemize     |
| ~I~   | enumerate   |
| ~y~   | array       |
| ~b~   | frame       |
| ~a~   | align       |
| ~A~   | align*      |
| ~n~   | alignat     |
| ~N~   | alignat*    |
| ~r~   | eqnarray    |
| ~l~   | flalign     |
| ~L~   | flalign*    |
| ~g~   | gather      |
| ~G~   | gather*     |
| ~m~   | multline    |
| ~M~   | multline*   |
| ~c~   | cases       |
| ~ta~  | axiom       |
| ~tc~  | corollary   |
| ~tC~  | claim       |
| ~td~  | definition  |
| ~te~  | examples    |
| ~ts~  | exercise    |
| ~tl~  | lemma       |
| ~tp~  | proof       |
| ~tq~  | question    |
| ~tr~  | remark      |
| ~tt~  | theorem     |
|-----+-------------|

Delimiter Table

|-----+--------------------------------|
| Key | Delimiter                      |
|-----+--------------------------------|
| ~b~   | ~[foo]~                          |
| ~B~   | ~\left[foo\right]~               |
| ~c~   | ~\{foo\}~                        |
| ~C~   | ~\left\{foo\right\}~             |
| ~r~   | ~\langle foo\rangle~             |
| ~R~   | ~\left\langle foo \right\langle~ |
| ~p~   | ~(foo)~                          |
| ~P~   | ~\left(foo\right)~               |
|-----+--------------------------------|

Examples:

|-----------------------------------------------+-------------------------------------------------------+------------------------------------|
| Starting String (~$~ indicates cursor position) | keybind                                               | Result                             |
|-----------------------------------------------+-------------------------------------------------------+------------------------------------|
| \ti$lde{h}                                    | ~cic~ (change inside command)                           | \tilde{~$~}                          |
| \tilde{h$}                                    | ~cscc bar~ (change surrounding command to ~bar~)          | \bar{~$~}                            |
| =\(\sum_{i=1}^{n} i^2$\)=                       | ~cim~ (change inner math)                               | =\(~$~\)=                              |
| =\(\sum_{i=1}^{n} i^2$\)=                       | ~mtm~ (toggle surrounding math)                         | =\[\sum_{i=1}^{n} i^2$\]=            |
| =\[a$^2\]=                                      | ~csmeA~ (change surrounding math to environment ~align*~  | =\begin{align*}\n a^2 \n\end{align}= |
| =(\mu$_\nu)=                                    | ~csddP~ (change surrounding delimiter to ~\left( \right)~ | =\left(\mu$_\nu\right)=              |
|-----------------------------------------------+-------------------------------------------------------+------------------------------------|

#+begin_src emacs-lisp
  (use-package evil-tex
    :after (tex auctex)
    :diminish
    :hook ((org-mode LaTeX-mode tex-mode) . evil-tex-mode))
#+end_src

* Org
** Org Mode

#+begin_src emacs-lisp
  (use-package org
    :diminish (org-indent-mode)
    :config
    (setq org-hide-emphasis-markers t
          org-hide-block-startup t
          org-src-tab-acts-natively t
          org-src-window-setup 'split-window-below
          org-image-actual-width nil)
    :hook (org-mode . org-indent-mode))
#+end_src

** Org Bullets

This minor-mode shows org-mode bullets as UTF-8 characters.
   
#+begin_src emacs-lisp
  (use-package org-bullets
    :hook (org-mode . org-bullets-mode))
#+end_src

** Org FragTog

This minor-mode automatically toggles org-mode LaTeX fragments as the cursor enters and exits them.
   
#+begin_src emacs-lisp
  (use-package org-fragtog
    :hook (org-mode . org-fragtog-mode))
#+end_src
   
* Ivy
** Ivy

#+begin_src emacs-lisp
  (use-package ivy
    :diminish
    :bind
    (("M-x" . 'counsel-M-x)
     ("C-x C-f" . 'counsel-find-file)
     ("C-x b" . 'counsel-switch-buffer)
     ("C-h f" . 'counsel-describe-function)
     ("C-h v" . 'counsel-describe-variable)
     ("C-h s" . 'counsel-describe-symbol)
     ("C-h F" . 'counsel-describe-face)
     ("C-x L" . 'counsel-find-library)
     ("C-c C-r" . 'counsel-resume)
     ("C-`" . 'counsel-unicode-char))
    :init
    (ivy-mode 1))
#+end_src

** Ivy Rich

#+begin_src emacs-lisp
  (use-package ivy-rich
    :diminish
    :init
    (ivy-rich-mode 1))
#+end_src

** Ivy All-The-Icons

#+begin_src emacs-lisp
  (use-package all-the-icons-ivy-rich
    :diminish
    :init
    (all-the-icons-ivy-rich-mode 1))
#+end_src

** Counsel

#+begin_src emacs-lisp
  (use-package counsel
    :diminish
    :bind
    (("s-f" . swiper)
     ("s-g" . counsel-grep)))
#+end_src

** IBuffer

IBuffer is an advanced replacement for BufferMenu, which lets you operate on buffers in a Dired-fashion.

|---------+----------------------+--------------------------------------------|
| Keybind | Command              | Description                                |
|---------+----------------------+--------------------------------------------|
| ~C-x C-b~ | ibuffer-other-window | Opens an IBuffer buffer in another window. |
|---------+----------------------+--------------------------------------------|

#+begin_src emacs-lisp
  (use-package ibuffer
    :bind
    (("C-x C-b" . ibuffer-other-window))
    :config
    (setq-default ibuffer-show-empty-filter-groups nil)
    (setq ibuffer-display-summary t))
#+end_src

** IBuffer VC

IBuffer-VC is a package that integrates IBuffer with Version Control information.

#+begin_src emacs-lisp
  (use-package ibuffer-vc
    :after (ibuffer vc)
    :hook
    (ibuffer-mode . ibuffer-vc-set-filter-groups-by-vc-root))
#+end_src

* Company

#+begin_src emacs-lisp
  (use-package company
    :diminish
    :config
    (setq company-dabbrev-downcase 0
          company-idle-delay 0.2)
    :hook (after-init . global-company-mode))
#+end_src

** Company Box

#+begin_src emacs-lisp
  (use-package company-box
    :after (company)
    :diminish
    :hook (company-mode . company-box-mode))
#+end_src

** Company Prescient

#+begin_src emacs-lisp
  (use-package company-prescient
    :after (company)
    :diminish
    :hook (company-mode . company-prescient-mode))
#+end_src

** Company QuickHelp

#+begin_src emacs-lisp
  (use-package company-quickhelp
    :after (company)
    :diminish
    :bind
    (:map company-active-map
          ("C-c h" . company-quickhelp-manual-begin))
    :hook (company-mode . company-quickhelp-mode))
#+end_src

** Company Emoji

#+begin_src emacs-lisp
  (use-package company-emoji
    :after (company)
    :diminish
    :config
    (add-to-list 'company-backends 'company-emoji)
    (defun --set-emoji-font (frame)
      "Adjust the font settings of FRAME so Emacs can display Emoji properly."
      (set-fontset-font t 'symbol (font-spec :family "Apple Color Emoji") frame 'prepend))
    (--set-emoji-font nil)
    :hook (after-make-frame-functions . --set-emoji-font))
#+end_src

* Miscellaneous Packages
** Magit

#+begin_src emacs-lisp
  (use-package magit
    :diminish)
#+end_src

** Git Gutter

|-----------+--------------------------+-----------------------------------------------|
| Keybind   | Command                  | Description                                   |
|-----------+--------------------------+-----------------------------------------------|
| ~<SPC> g g~ | git-gutter:popout-hunk   | Pop out the modified chunk into a new buffer. |
| ~<SPC> g s~ | git-gutter:stage-hunk    | Stage the modified chunk.                     |
| ~<SPC> g j~ | git-gutter:next-diff     | Move to the next modified chunk.              |
| ~<SPC> g k~ | git-gutter:previous-diff | Move to the previous modified chunk.          |
| ~<SPC> g R~ | git-gutter:revert-hunk   | Revert the modified chunk.                    |
|-----------+--------------------------+-----------------------------------------------|

#+begin_src emacs-lisp
  (use-package git-gutter
    :config
    (evil-leader/set-key
      "g g" 'git-gutter:popup-hunk
      "g s" 'git-gutter:stage-hunk
      "g j" 'git-gutter:next-diff
      "g k" 'git-gutter:previous-diff
      "g R" 'git-gutter:revert-hunk)
    (custom-set-variables
     '(git-gutter:update-interval 2)
     '(git-gutter:added-sign "+")
     '(git-gutter:modified-sign "*")
     '(git-gutter:deleted-sign "-")
     '(git-gutter:hide-gutter nil))
    (set-face-background 'git-gutter:added "#00b894")
    (set-face-foreground 'git-gutter:added "#00b894")
    (set-face-background 'git-gutter:modified "#fdcb6e")
    (set-face-foreground 'git-gutter:modified "#fdcb6e")
    (set-face-background 'git-gutter:deleted "#ff7675")
    (set-face-foreground 'git-gutter:deleted "#ff7675")
    :init
    (global-git-gutter-mode 1))
#+end_src

** Winum

Winum is a minor-mode to navigate windows and frames using numbers.

|---------+-----------------------+---------------------|
| Keybind | Command               | Description         |
|---------+-----------------------+---------------------|
| ~S-1~     | winum-select-window-1 | Switch to window 1. |
| ~S-2~     | winum-select-window-2 | Switch to window 2. |
| ~S-3~     | winum-select-window-3 | Switch to window 3. |
| ~S-4~     | winum-select-window-4 | Switch to window 4. |
| ~S-5~     | winum-select-window-5 | Switch to window 5. |
| ~S-6~     | winum-select-window-6 | Switch to window 6. |
| ~S-7~     | winum-select-window-7 | Switch to window 7. |
| ~S-8~     | winum-select-window-8 | Switch to window 8. |
| ~S-9~     | winum-select-window-9 | Switch to window 9. |
| ~S-0~     | winum-select-window-0 | Switch to window 0. |
|---------+-----------------------+---------------------|

#+begin_src emacs-lisp
  (use-package winum
    :init
    (setq winum-auto-setup-mode-line t)
    (setq winum-keymap
            (let ((map (make-sparse-keymap)))
              (define-key map (kbd "s-1") 'winum-select-window-1)
              (define-key map (kbd "s-2") 'winum-select-window-2)
              (define-key map (kbd "s-3") 'winum-select-window-3)
              (define-key map (kbd "s-4") 'winum-select-window-4)
              (define-key map (kbd "s-5") 'winum-select-window-5)
              (define-key map (kbd "s-6") 'winum-select-window-6)
              (define-key map (kbd "s-7") 'winum-select-window-7)
              (define-key map (kbd "s-8") 'winum-select-window-8)
              (define-key map (kbd "s-9") 'winum-select-window-9)
              (define-key map (kbd "s-0") 'winum-select-window-0)
              map))
    :config
    (winum-mode))
#+end_src

** EShell Toggle

This package shows/hides a eshell buffer at the bottom of the active window with the directory of its buffer.

|---------+---------------+-------------------------------|
| Keybind | Command       | Description                   |
|---------+---------------+-------------------------------|
| ~C-=~     | eshell-toggle | Toggles a eshell side-buffer. |
|---------+---------------+-------------------------------|

#+begin_src emacs-lisp
  (use-package eshell-toggle
    :config
    (defun eshell-toggle--make-buffer-name ()
      "Generate EShell-Toggle buffer name."
      "*eshell-toggle*")
    :bind
    (("C-=" . eshell-toggle)))
#+end_src

** Elcord

Elcord is a minor-mode that integrates with Discord's Rich Presence API.
   
#+begin_src emacs-lisp
  (use-package elcord
    :init
    (elcord-mode))
#+end_src

** Which Key

WhichKey is a minor-mode that displays available keybinds in a popup side-buffer.

#+begin_src emacs-lisp
  (use-package which-key
    :diminish
    :config
    (which-key-setup-side-window-bottom)
    (which-key-setup-minibuffer)
    (setq which-key-idle-delay 0.5)
    :init
    (which-key-mode))
#+end_src
